import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import XSidebar from "@/components/XSidebar";
import XTopbar from "@/components/XTopbar";
import XMainContent from "@/components/XMainContent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen">
          <XSidebar />
          <div className="flex-1 flex flex-col overflow-hidden">
            <XTopbar />
            <XMainContent>{children}</XMainContent>
          </div>
        </div>
      </body>
    </html>
  );
}
