import '@/assets/tailwind-light/theme.css';
import XMainContent from '@/components/XMainContent';
import XSidebar from '@/components/XSidebar';
import XTopbar from '@/components/XTopbar';
import { ToastProvider } from '@/contexts/ToastContext';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/primereact.min.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen">
          <XSidebar />
          <div className="flex-1 flex flex-col overflow-hidden">
            <XTopbar />
            <XMainContent>
              <PrimeReactProvider>
                <ToastProvider>{children}</ToastProvider>
              </PrimeReactProvider>
            </XMainContent>
          </div>
        </div>
      </body>
    </html>
  );
}
